;;; Automatically generated by ‘recentf’ on Fri Feb  2 14:14:19 2024.

(setq recentf-list
      '(
        "/home/christopher/.emacs"
        "/home/christopher/Documents/work/gitlabs/derant_angle_app/backend_flask/config.py"
        "/home/christopher/Documents/work/gitlabs/derant_angle_app/backend_flask/init.sql"
        "/home/christopher/Documents/work/sql.txt"
        "/home/christopher/.emacs.d/elpa/doom-modeline-now-playing-20210831.1442/doom-modeline-now-playing-autoloads.el"
        "/home/christopher/.emacs.d/elpa/doom-themes-20230916.2032/doom-themes-autoloads.el"
        "/home/christopher/.authinfo"
        "/home/christopher/.emacs.d/elpa/which-key-20230905.2128/which-key-autoloads.el"
        "/home/christopher/.emacs.d/elpa/counsel-projectile-20211004.2003/counsel-projectile-autoloads.el"
        "/home/christopher/.emacs.d/elpa/projectile-20231013.1509/projectile-autoloads.el"
        "/home/christopher/.emacs.d/elpa/all-the-icons-ivy-rich-20230420.1234/all-the-icons-ivy-rich-autoloads.el"
        "/home/christopher/.emacs.d/elpa/ivy-prescient-20221216.112/ivy-prescient-autoloads.el"
        "/home/christopher/.emacs.d/elpa/prescient-20230909.2336/prescient-autoloads.el"
        "/home/christopher/.emacs.d/elpa/ivy-rich-20230425.1422/ivy-rich-autoloads.el"
        "/home/christopher/.emacs.d/elpa/ido-completing-read+-20210529.1318/ido-completing-read+-autoloads.el"
        "/home/christopher/.emacs.d/elpa/magit-section-20231014.1405/magit-section-autoloads.el"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
