;;; Automatically generated by ‘recentf’ on Thu Sep 19 18:44:52 2024.

(setq recentf-list
      '(
        "~/.emacs"
        "~/.emacs.d/var/bookmark-default.el"
        "~/.emacs.d/elpa/counsel-projectile-20211004.2003/counsel-projectile-autoloads.el"
        "~/.emacs.d/elpa/all-the-icons-ivy-rich-20230420.1234/all-the-icons-ivy-rich-autoloads.el"
        "~/.emacs.d/elpa/ivy-rich-20230425.1422/ivy-rich-autoloads.el"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
