;;; Automatically generated by ‘recentf’ on Mon Jan  3 15:34:18 2022.

(setq recentf-list
      '(
        "/home/christopher/org/gtd/tickler.org"
        "/home/christopher/org/gtd/inbox.org"
        "/home/christopher/org/gtd/gtd.org"
        "/home/christopher/org/org.org"
        "/home/christopher/Documents/Work/Derant/derant_angle_app/frontend_vue/src/views/SetAlarmNotis.vue"
        "/home/christopher/Documents/Work/Derant/derant_angle_app/frontend_vue/src/views/Login.vue"
        "/home/christopher/Documents/Work/Derant/derant_angle_app/frontend_vue/src/views/AlarmTriggers.vue"
        "/home/christopher/Documents/Work/Derant/derant_angle_app/backend_flask/angle/models.py"
        "/home/christopher/Documents/Work/Derant/derant_angle_app/backend_flask/angle/resources/delete_autofilter.py"
        "/home/christopher/Documents/Work/Derant/derant_angle_app/backend_flask/angle/resources/create_auto_filter.py"
        "/home/christopher/Documents/Work/Derant/derant_angle_app/backend_flask/angle/resources/get_auto_filter.py"
        "/home/christopher/.emacs.d/package.el"
        "/home/christopher/.emacs"
        "/home/christopher/Documents/Work/Derant/derant_angle_app/frontend_vue/src/views/AnalysisNetwork.vue"
        "/home/christopher/Documents/Work/Derant/derant_angle_app/backend_flask/angle/resources/save_filter.py"
        "/home/christopher/Documents/Work/Derant/derant_angle_app/frontend_vue/src/languages/en.js"
        "/home/christopher/Documents/Work/Derant/derant_angle_app/frontend_vue/src/languages/da.js"
        "/home/christopher/Documents/Work/Derant/derant_angle_app/frontend_vue/src/views/SetApiKey.vue"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
