
;; ----- smex-history -----
(
 comment-box
 comment-region
 replace-string
 uncomment-region
 package-delete
 package-install
 find-file
)

;; ----- smex-data -----
(
 (find-tag . 1)
 (find-file . 7384)
 (package-install . 77)
 (comment-box . 140)
 (package-delete . 14)
 (uncomment-region . 308)
 (highlight-indentation-mode . 27)
 (highlight-indent-guides-mode . 11)
 (fountain-mode . 3)
 (jinja2-mode . 4)
 (web-mode-set-engine . 2)
 (package-refresh-contents . 25)
 (comment-region . 1158)
 (package-list-packages . 9)
 (prettier-js-mode . 9)
 (prettier-js . 2)
 (web-mode . 22)
 (replace-string . 182)
 (eww-mode . 1)
 (eww-open-file . 1)
 (python-mode . 2)
 (ftp . 1)
 (comment-set-column . 1)
 (profiler-start . 9)
 (profiler-report . 14)
 (linum-mode . 40)
 (font-lock-mode . 3)
 (package-menu-mode . 4)
 (emacs-version . 3)
 (nlinum-mode . 7)
 (nlinum-relative-off . 4)
 (hl-line-mode . 4)
 (vlf . 1)
 (flycheck-mode . 12)
 (all-the-icons-install-fonts . 3)
 (minions-mode . 3)
 (column-number-mode . 1)
 (spaceline-install . 1)
 (moody-replace-vc-mode . 2)
 (flycheck-verify-setup . 1)
 (untabify . 1)
 (company-elisp . 1)
 (centaur-tabs-mode . 7)
 (tool-bar-mode . 1)
 (compile . 1)
 (fountain-export-buffer-to-fountain . 1)
 (fountain-export-buffer . 1)
 (fountain-mode-menu . 1)
 (fountain-export-default . 1)
 (web-mode-disable . 6)
 (Info-index . 1)
 (flx-ido-mode . 1)
 (vue-mode . 1)
 (aggressive-indent-mode . 5)
 (web-mode-buffer-indent . 1)
 (indent-sexp . 1)
 (electric-indent-mode . 1)
 (company-mode . 5)
 (mode-icons-mode . 2)
 (rainbow-delimiters-mode . 1)
 (yascroll:show-scroll-bar . 1)
 (customize . 3)
 (dockerfile-mode . 4)
 (comment-or-uncomment-region . 2)
 (ediff-files . 1)
 (magit-next-line . 1)
 (shell-command-with-editor-mode . 1)
 (jdee-package-update . 1)
 (list-packages . 1)
 (indent-relative . 2)
 (web-mode-buffer-fontify . 1)
 (drag-stuff-mode . 1)
 (nyan-mode . 1)
 (web-mode-debug . 1)
 (jit-lock-debug-mode . 1)
 (display-line-numbers-mode . 3)
 (package-show-package-list . 1)
 (lisp-mode . 3)
 (org-mode . 3)
 (ido-mode . 3)
 (next-buffer . 2)
 (comint-delchar-or-maybe-eof . 2)
 (indent-region . 1)
 (python-indent-shift-left . 37)
 (python-indent-shift-right . 33)
 (grep-find . 5)
 (grep . 7)
 (find-name-dired . 1)
 (kill-line . 1)
 (common-lisp-mode . 3)
 (markdown-mode . 1)
 (org-increase-number-at-point . 1)
 (org-do-promote . 1)
 (auto-package-update-now . 12)
 (bison-mode . 1)
 (package-initialize . 2)
 (byte-recompile-directory . 2)
 (package-reinstall . 3)
 (highlight-uses-mode . 1)
 (change-log-mode . 1)
 (conventional-changelog-transform . 1)
 (debian-changelog-mode . 1)
 (customize-group . 2)
 (chatgpt-arcana-chat-mode . 2)
 (chatgpt-arcana-hydra/chatgpt-arcana-start-chat-and-exit . 1)
 (gptel . 7)
 (gptel-menu . 13)
 (gptel-send . 8)
 (ivy-mode . 4)
 (smex . 2)
 (ivy-rich-mode . 2)
 (counsel-find-file . 2)
 (which-key-mode . 2)
 (chatgpt-shell . 4)
 (chatgpt-shell-prompt . 1)
)
