
;; ----- smex-history -----
(
 find-file
 comment-box
 replace-string
 uncomment-region
 comment-region
 linum-mode
 python-mode
)

;; ----- smex-data -----
(
 (find-tag . 1)
 (find-file . 4461)
 (package-install . 56)
 (comment-box . 7)
 (package-delete . 9)
 (uncomment-region . 243)
 (highlight-indentation-mode . 27)
 (highlight-indent-guides-mode . 10)
 (fountain-mode . 3)
 (jinja2-mode . 4)
 (web-mode-set-engine . 2)
 (package-refresh-contents . 19)
 (comment-region . 850)
 (package-list-packages . 7)
 (prettier-js-mode . 9)
 (prettier-js . 2)
 (web-mode . 21)
 (replace-string . 98)
 (eww-mode . 1)
 (eww-open-file . 1)
 (python-mode . 2)
 (ftp . 1)
 (comment-set-column . 1)
 (profiler-start . 9)
 (profiler-report . 14)
 (linum-mode . 25)
 (font-lock-mode . 3)
 (package-menu-mode . 4)
 (emacs-version . 3)
 (nlinum-mode . 7)
 (nlinum-relative-off . 4)
 (hl-line-mode . 4)
 (vlf . 1)
 (flycheck-mode . 12)
 (all-the-icons-install-fonts . 1)
 (minions-mode . 3)
 (column-number-mode . 1)
 (spaceline-install . 1)
 (moody-replace-vc-mode . 2)
 (flycheck-verify-setup . 1)
 (untabify . 1)
 (company-elisp . 1)
 (centaur-tabs-mode . 7)
 (tool-bar-mode . 1)
 (compile . 1)
 (fountain-export-buffer-to-fountain . 1)
 (fountain-export-buffer . 1)
 (fountain-mode-menu . 1)
 (fountain-export-default . 1)
 (web-mode-disable . 6)
 (Info-index . 1)
 (flx-ido-mode . 1)
 (vue-mode . 1)
 (aggressive-indent-mode . 5)
 (web-mode-buffer-indent . 1)
 (indent-sexp . 1)
 (electric-indent-mode . 1)
 (company-mode . 5)
 (mode-icons-mode . 2)
 (rainbow-delimiters-mode . 1)
 (yascroll:show-scroll-bar . 1)
 (customize . 3)
 (dockerfile-mode . 4)
 (comment-or-uncomment-region . 2)
 (ediff-files . 1)
 (magit-next-line . 1)
 (shell-command-with-editor-mode . 1)
 (jdee-package-update . 1)
 (list-packages . 1)
 (indent-relative . 2)
 (web-mode-buffer-fontify . 1)
 (drag-stuff-mode . 1)
 (nyan-mode . 1)
 (web-mode-debug . 1)
 (jit-lock-debug-mode . 1)
 (display-line-numbers-mode . 3)
 (package-show-package-list . 1)
 (lisp-mode . 3)
 (org-mode . 3)
 (ido-mode . 3)
 (next-buffer . 2)
 (comint-delchar-or-maybe-eof . 2)
 (indent-region . 1)
 (python-indent-shift-left . 7)
 (python-indent-shift-right . 6)
 (grep-find . 5)
 (grep . 7)
 (find-name-dired . 1)
 (kill-line . 1)
 (common-lisp-mode . 1)
)
